// import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import dynamic from 'next/dynamic';

const TVChartContainer = dynamic(
  () => import('../components/TVChartContainer/TradingView'),
  { ssr: false }
);

const Home = () => {
  return (
    <div className={styles.container} style={{ background: '#57575f' }}>
      <Head>
        <title>TradingView</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ color: 'white' }}>TradingView Chart Nextjs</h1>
        <TVChartContainer />
      </main>
    </div>
  );
};

export default Home;
